sudo: required
dist: trusty

language: node_js
node_js:
- "6"

addons:
  chrome: stable

before_install:
  - cd git-visualize
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - ng build --prod

script:
  - ng test --single-run --code-coverage
  - ng lint

after_success:
- bash <(curl -s https://codecov.io/bash)

cache:
  bundler: true
  directories: node_modules
